export const strings = {
    loadingText: 'در حال بارگذاری...',
    ContentType: 'application/json',
    savedSuccessfully:"با موفقیت ثبت شد",
    updateCarTool: {
      updateCarToolHeader: 'به روزرسانی ابزار خودرو',
      mileageLabel: 'مسافت پیموده شده',
      enterMileagePlaceholder: 'مسافت پیموده شده را وارد کنید',
      customFieldsSeparator: 'فیلدهای سفارشی',
      saveButton: 'ذخیره',
      naPlaceholder: 'N/A',
    },
    carSetupScreenStrings: {
      loadingText: 'در حال بارگذاری...',
      errorTitle: 'خطا',
      errorMessage: 'دریافت داده‌ها ناموفق بود',
      successTitle: 'موفقیت',
      successUpdateMessage: 'داده‌ها با موفقیت به روز شدند',
      resetSuccessMessage: 'تنظیمات خودرو بازنشانی شد.',
      resetErrorMessage: 'بازنشانی تنظیمات خودرو ناموفق بود',
      updateButtonTitle: 'به روزرسانی داده‌ها',
      resetButtonTitle: 'بازنشانی داده‌ها',
    },
    settingScreenStrings: {
      loadingText: 'در حال بارگذاری...',
      loggedOutTitle: 'خروج',
      loggedOutMessage: 'شما از سیستم خارج شده‌اید.',
      logoutErrorTitle: 'خطا',
      logoutErrorMessage: 'خروج از سیستم ناموفق بود. لطفا دوباره تلاش کنید.',
      editProfileButton: 'ویرایش پروفایل',
      changePasswordButton: 'تغییر رمز عبور',
      logoutButton: 'خروج',
    },
    notificationScreenStrings: {
      loadingText: 'در حال بارگذاری...',
      errorTitle: 'خطا',
      errorMessage: 'دریافت داده‌های خودرو ناموفق بود',
      filterFieldName: 'فیلتر',
      oilFieldName: 'روغن',
      
    },
    carsListScreenStrings: {
      loadingText: 'در حال بارگذاری...',
      errorFetchingCars: 'خطا در دریافت خودروهای کاربر',
    },
    customFieldScreenStrings: {
      loadingText: 'در حال بارگذاری...',
      errorFetchingCustomField: 'خطا در دریافت فیلد شخصی',
      errorDavingCustomField: 'خطا در ثبت فیلد شخصی',
      saveButton: 'ذخیره',
      namePlaceholder: 'نام را وارد کنید',
      mileagePlaceholder: 'مسافت پیموده شده را وارد کنید',
      yearPlaceholder: 'سال',
      monthPlaceholder: 'ماه',
      lastMileagePlaceholder: 'آخرین مسافت پیموده شده را وارد کنید',
      name: 'نام:',
      mileagePerChange:"مقدار مسافت بین هر تعویض:",
      durationPerChange:"مدت زمان بین هر تعویض:",
      lastMileageChanged: " آخرین کیلومتر تعویض:",
      lastChangedDate: " آخرین تاریخ تعویض:",
      dateBase :"بر اساس تاریخ",
      mileageBase :"بر اساس مسافت",

      selectDateText: 'تاریخ را انتخاب کنید',
    },
    carDetialScreenStrings: {
      loadingText: 'در حال بارگذاری...',
      errorFetchingDashboard: 'خطا در دریافت داشبورد خودرو کاربر',
      customFieldButton: 'فیلد شخصی',
      carSetupButton: 'تغییر تنظیمات پیش‌فرض',
      editInfoButton: 'بروزرسانی وضعیت خودرو',
      updateToolButton: 'به روزرسانی ابزار',
    },
    addEditCarInfoFirstScreenStrings: {
      namePlaceholder: 'نام',
      selectCompanyLabel: 'انتخاب شرکت خودرو',
      selectModelLabel: 'انتخاب مدل خودرو',
      mileagePlaceholder: 'مسافت پیموده شده',
      mileage: 'مسافت',

      nextButton: 'بعدی',
    },
    addEditCarInfoSecondScreenStrings: {
      oilsSeparator: 'روغن‌ها',
      filtersSeparator: 'فیلترها',
      engineOilPlaceholder: 'روغن موتور',
      gearboxOilPlaceholder: 'روغن گیربکس',
      hydraulicFluidPlaceholder: 'روغن هیدرولیک',
      oilFilterPlaceholder: 'فیلتر روغن',
      fuelFilterPlaceholder: 'فیلتر سوخت',
      airFilterPlaceholder: 'فیلتر هوا',
      cabinAirFilterPlaceholder: 'فیلتر هوای کابین',
      timingBeltPlaceholder: 'تسمه تایمینگ',
      alternatorBeltPlaceholder: 'تسمه دینام',
      frontBrakePadsPlaceholder: 'لنت ترمز جلو',
      rearBrakePadsPlaceholder: 'لنت ترمز عقب',
      sparkPlugPlaceholder: 'شمع',
      frontSuspensionPlaceholder: 'تعلیق جلو',
      clutchPlatePlaceholder: 'صفحه کلاچ',
      saveButton: 'ذخیره',
      errorInSavingCar: 'خطا در ثبت خودرو',
    },
    login: {
      title: 'ورود',
      emailPlaceholder: 'ایمیل',
      passwordPlaceholder: 'رمز عبور',
      loginButton: 'ورود',
      noAccount: "حساب کاربری ندارید؟",
      signupLink: 'ثبت نام',
      alertTitle: 'ورود ناموفق بود',
      alertMessage: 'نام کاربری یا رمز عبور اشتباه است',
      errorTitle: 'خطا',
      errorMessage: 'در حین ورود به سیستم خطایی رخ داد. لطفا بعدا دوباره تلاش کنید.',
    },
    registration: {
      emailRequired: "ایمیل اجباری است",
      emailInvalid: "لطفا از یک ایمیل واقعی استفاده کنید",
      firstNameRequired: "نام اجباری است",
      lastNameRequired: "نام خانوادگی اجباری است",
      passwordRequired: "رمز عبور اجباری است",
      passwordCanNotJustBeSpace: "رمز عبور نمیتواند تنها فاصله باشد",
      passwordMismatch: "رمز عبور و تکرار آن تطابق ندارند",
      title: 'ثبت نام',
      firstNamePlaceholder: 'نام',
      lastNamePlaceholder: 'نام خانوادگی',
      emailPlaceholder: 'ایمیل',
      passwordPlaceholder: 'رمز عبور',
      rePasswordPlaceholder: 'تکرار رمز عبور',
      registerButton: 'ثبت نام',
      haveAccount: 'حساب کاربری دارید؟',
      loginLink: 'ورود',
      errorTitle: 'خطا',
      errorMessage: 'خطایی غیرمنتظره رخ داد. لطفا بعدا دوباره تلاش کنید.',
      alertTitle: 'خطا',
      alertMessage: 'لطفا تمام فیلدها را به درستی پر کنید.',
      registrationFailed: 'ثبت نام ناموفق بود. لطفا دوباره تلاش کنید.',
      registrationSuccess: 'ثبت نام با موفقیت انجام شد',
    },
    mainStack: {
      Login: 'ورود',
      Registration: 'ثبت نام',
      CarScreen: 'صفحه خودرو',
      Setting: 'تنظیمات',
      EditProfile: 'ویرایش پروفایل',
      ChangePassword: 'تغییر رمز عبور',
      Home: 'خانه',
      CustomFieldList: ' فیلد شخصی',
      Car: 'خودرو',
      AddingCar: 'اضافه کردن خودرو',
      ErrorDeletingCustomField: 'خطا در حذف فیلد شخصی:',
      ErrorDeletingCar: 'خطا در حذف خودرو:',
      Notification : "اعلانات",
      deleteCustomFieldTitle:"حذف فیلد شخصی",
      deleteQuestionText:"مطمئنید که میخواهید حذف کنید؟",
      deleteCarTitle:"حذف خودرو",
      errorInDeleteing :"خطا در حذف مجدد تلاش کنید",
      yesMessage:"بله",
      noMessage: "خیر"
    },
    defaultToolsStrings: {
      engine_oil: "روغن موتور",
      hydraulic_fluid: "روغن هیدرولیک",
      gearbox_oil: "روغن گیربکس",
      oil_filter: "فیلتر روغن",
      fuel_filter: "فیلتر سوخت",
      air_filter: "فیلتر هوا",
      cabin_air_filter: "فیلتر هوای کابین",
      timing_belt: "تسمه تایم",
      timing_belt_max_year: "تسمه تایم (حداکثر سال‌ها)",
      alternator_belt: "تسمه دینام",
      front_brake_pads: "لنت ترمز جلو",
      rear_brake_pads: "لنت ترمز عقب",
      spark_plug: "شمع",
      front_suspension: "سیستم تعلیق جلو",
      clutch_plate: "صفحه کلاچ",
      mileage: " مسافت پیموده شده"

    },
    profileString: {
      Email: "ایمیل",
      firstNamePlaceholder: 'نام',
      lastNamePlaceholder: 'نام خانوادگی',
      save: "ثبت",
      changePassword:"تغییر رمز",
      oldPassword:"رمز عبور فعلی",
      newPassword:"رمز جدید",
      repeatNewPassword:"تکرار رمز",
      newPasswordAndConfirmationError:"رمز جدید و تکرار آن همخوانی ندارند",
      errorInUpdatingProfile:"خطا در بروزرسانی اطلاعات کاربری"
    },
    
  };
  