// strings.js

export const strings = {
  ContentType: 'application/json',
  updateCarTool: {
    updateCarToolHeader: 'Update Car Tool',
    mileageLabel: 'Mileage',
    enterMileagePlaceholder: 'Enter mileage',
    customFieldsSeparator: 'Custom fields',
    saveButton: 'Save',
    naPlaceholder: 'N/A',
  },
  carSetupScreenStrings: {
    loadingText: 'Loading...',
    errorTitle: 'Error',
    errorMessage: 'Failed to fetch data',
    successTitle: 'Success',
    successUpdateMessage: 'Data updated successfully',
    resetSuccessMessage: 'Car setup has been reset.',
    resetErrorMessage: 'Failed to reset car setup',
    updateButtonTitle: 'Update Data',
    resetButtonTitle: 'Reset Data',
  },
  settingScreenStrings: {
    loadingText: 'Loading...',
    loggedOutTitle: 'Logged Out',
    loggedOutMessage: 'You have been logged out.',
    logoutErrorTitle: 'Error',
    logoutErrorMessage: 'Failed to log out. Please try again.',
    editProfileButton: 'Edit Profile',
    changePasswordButton: 'Change Password',
    logoutButton: 'Logout',
  },
  notificationScreenStrings: {
    loadingText: 'Loading...',
    errorTitle: 'Error',
    errorMessage: 'Failed to fetch car data',
    filterFieldName: 'filter',
    oilFieldName: 'oil',
  },
  carsListScreenStrings: {
    loadingText: 'Loading...',
    errorFetchingCars: 'Error fetching user cars',
  },
  customFieldScreenStrings: {
    loadingText: 'Loading...',
    errorFetchingCustomField: 'Error fetching custom field',
    saveButton: 'Save',
    namePlaceholder: 'Enter name',
    mileagePlaceholder: 'Enter mileage per change',
    yearPlaceholder: 'Year',
    monthPlaceholder: 'Month',
    lastMileagePlaceholder: 'Enter last mileage changed',
    selectDateText: 'Select Date',
  },
  carDetialScreenStrings: {
    loadingText: 'Loading...',
    errorFetchingDashboard: 'Error fetching user car dashboard',
    customFieldButton: 'Custom Field',
    carSetupButton: 'Car Setup',
    editInfoButton: 'Edit Info',
    updateToolButton: 'Update Tool',
  },
  addEditCarInfoFirstScreenStrings: {
    namePlaceholder: 'Name',
    selectCompanyLabel: 'Select Car Company',
    selectModelLabel: 'Select Car Model',
    mileagePlaceholder: 'Mileage',
    nextButton: 'Next',
  },
  addEditCarInfoSecondScreenStrings: {
    oilsSeparator: 'Oils',
    filtersSeparator: 'Filters',
    engineOilPlaceholder: 'Engine Oil',
    gearboxOilPlaceholder: 'Gearbox Oil',
    hydraulicFluidPlaceholder: 'Hydraulic Fluid',
    oilFilterPlaceholder: 'Oil Filter',
    fuelFilterPlaceholder: 'Fuel Filter',
    airFilterPlaceholder: 'Air Filter',
    cabinAirFilterPlaceholder: 'Cabin Air Filter',
    timingBeltPlaceholder: 'Timing Belt',
    alternatorBeltPlaceholder: 'Alternator Belt',
    frontBrakePadsPlaceholder: 'Front Brake Pads',
    rearBrakePadsPlaceholder: 'Rear Brake Pads',
    sparkPlugPlaceholder: 'Spark Plug',
    frontSuspensionPlaceholder: 'Front Suspension',
    clutchPlatePlaceholder: 'Clutch Plate',
    saveButton: 'Save',
  },
  login: {
    title: 'Login',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    loginButton: 'Login',
    noAccount: "Don't have an account?",
    signupLink: 'Sign Up',
    alertTitle: 'Login failed',
    alertMessage: 'Please check your credentials',
    errorTitle: 'Error',
    errorMessage: 'An error occurred during login. Please try again later.',
    contentType: 'Content-Type',
  },
  registration: {
    title: 'Registration',
    firstNamePlaceholder: 'First Name',
    lastNamePlaceholder: 'Last Name',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    rePasswordPlaceholder: 'Repeat Password',
    registerButton: 'Register',
    haveAccount: 'Already have an account?',
    loginLink: 'Login',
    errorTitle: 'Error',
    errorMessage: 'An unexpected error occurred. Please try again later.',
    alertTitle: 'Error',
    alertMessage: 'Please fill out all fields correctly.',
    registrationFailed: 'Registration failed. Please try again.',
    registrationSuccess: 'Registered successfully',
    contentType: 'Content-Type',
  },
};
